// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entry.HealthResponse"
                        }
                    }
                }
            }
        },
        "/internal/operations/{id}/file": {
            "get": {
                "description": "Streams the update file for an operation. Supports HTTP range requests and is",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Download the uploaded update file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "416": {
                        "description": "Requested Range Not Satisfiable"
                    }
                }
            }
        },
        "/operations": {
            "get": {
                "description": "Searches update operations indexed in Elasticsearch. Results can be filtered",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Search update operations",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"hello-service\"",
                        "description": "Filter by service name",
                        "name": "service",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "PENDING",
                            "DISPATCHED",
                            "TRANSFERRED",
                            "RUNNING",
                            "BACKUP_CREATED",
                            "APPLYING",
                            "HEALTH_CHECKING",
                            "SUCCEEDED",
                            "FAILED",
                            "ROLLING_BACK",
                            "ROLLBACK_HEALTH_CHECKING",
                            "ROLLED_BACK",
                            "ROLLBACK_FAILED"
                        ],
                        "type": "string",
                        "example": "\"PENDING\"",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"node-1\"",
                        "description": "Filter by worker node id",
                        "name": "node_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "example": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/search.SearchResult"
                        }
                    },
                    "503": {
                        "description": "search temporarily unavailable",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/updates": {
            "post": {
                "description": "Creates a new pending update operation for a service on a worker node and",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Create an update operation",
                "parameters": [
                    {
                        "description": "Service and target node",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entry.CreateUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/entry.CreateUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body or missing service/node_id",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "node not found",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "node is not online",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "failed to create the operation",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/updates/{id}": {
            "get": {
                "description": "Returns the current status of the update operation identified by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Get update operation status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entry.OperationStatusResponse"
                        }
                    },
                    "404": {
                        "description": "operation not found",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/uploads": {
            "post": {
                "description": "Creates a new tus upload session for an update operation.\nThe operation must already exist and be in the PENDING state.\nThe Upload-Metadata header must contain the base64-encoded operation_id and filename values.",
                "consumes": [
                    "application/offset+octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uploads"
                ],
                "summary": "Create a tus resumable upload",
                "parameters": [
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Tus protocol version",
                        "name": "Tus-Resumable",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Total upload size in bytes",
                        "name": "Upload-Length",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base64-encoded metadata: operation_id and filename",
                        "name": "Upload-Metadata",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Upload created",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "URL of the created upload resource"
                            }
                        }
                    },
                    "400": {
                        "description": "missing or invalid headers, or operation is not pending",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "operation not found",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/uploads/{id}": {
            "patch": {
                "description": "Appends a chunk of bytes at Upload-Offset.\nWhen the upload is complete the server computes the file SHA256, stores the file metadata and dispatches the operation to the target worker node.",
                "consumes": [
                    "application/offset+octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uploads"
                ],
                "summary": "Append a chunk to a tus upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID returned in the Location header of POST /uploads",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Tus protocol version",
                        "name": "Tus-Resumable",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Byte offset of this chunk within the upload",
                        "name": "Upload-Offset",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Raw chunk bytes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Final chunk accepted; file metadata returned",
                        "schema": {
                            "$ref": "#/definitions/entry.FileUploadResponse"
                        }
                    },
                    "204": {
                        "description": "Chunk accepted, upload not yet complete",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid content type, offset or checksum",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "upload not found",
                        "schema": {
                            "$ref": "#/definitions/entry.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entry.CreateUpdateRequest": {
            "type": "object",
            "properties": {
                "node_id": {
                    "type": "string",
                    "example": "worker-node"
                },
                "service": {
                    "type": "string",
                    "enum": [
                        "hello-service",
                        "config-service",
                        "test-service"
                    ],
                    "example": "hello-service"
                }
            }
        },
        "entry.CreateUpdateResponse": {
            "type": "object",
            "properties": {
                "operation_id": {
                    "type": "string",
                    "example": "op-3f2a91c0"
                }
            }
        },
        "entry.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "entry.FileUploadResponse": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string",
                    "example": "config.yaml"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1048576
                },
                "operation_id": {
                    "type": "string",
                    "example": "op-3f2a91c0"
                },
                "sha256": {
                    "type": "string",
                    "example": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
                }
            }
        },
        "entry.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "entry.OperationStatusResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "op-3f2a91c0"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "DISPATCHED",
                        "TRANSFERRED",
                        "RUNNING",
                        "BACKUP_CREATED",
                        "APPLYING",
                        "HEALTH_CHECKING",
                        "SUCCEEDED",
                        "FAILED",
                        "ROLLING_BACK",
                        "ROLLBACK_HEALTH_CHECKING",
                        "ROLLED_BACK",
                        "ROLLBACK_FAILED"
                    ],
                    "example": "PENDING"
                }
            }
        },
        "search.OperationDocument": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "search.SearchResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.OperationDocument"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Updater Service API",
	Description:      "Deploys configuration and binary updates to managed services. Clients create",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
