services:
  hello-service:
    image: python:3-alpine
    container_name: hello-service
    ports:
      - "18080:8080"
    volumes:
      - ./hello-service:/app:ro
    working_dir: /app
    command:
      - python
      - app.py
    environment:
      CONFIG_PATH: /app/config.yaml
    restart: "no"

  config-service:
    image: alpine:3.22
    container_name: config-service
    command:
      - /bin/sh
      - -c
      - |
        echo "config-service started"
        while true; do
          echo "config-service is alive: $(date)"
          sleep 5
        done
    restart: "no"

  test-service:
    image: alpine:3.22
    container_name: test-service
    command:
      - /bin/sh
      - -c
      - |
        echo "test-service started"
        while true; do
          echo "test-service is alive: $(date)"
          sleep 5
        done
    restart: "no"